### ISSUE TITLE
Strange implementation

### ISSUE THREAD

**Issue by mignev** [jgmdev/ddos-deflate#2]
Hello guys,

awesome script work like a charm but there is something strange here :)

Is there any meaningful explanation of those 2 lines of code:
https://github.com/jgmdev/ddos-deflate/blob/master/src/ddos.sh#L125-L126

**Comment by maxcuttins** [comment]
Hi,

basically this version of the script recycle the ignore.ip list in order 
to avoid double ban.
This is why we decided to fork and have a ban database instead of 
recycle the ignore lists which should rest untouched.
It should be considerad dangerous as a bug:

    /If you restart your server before the banned IP have been deleted
    then the banned IP will rest in the whitelist undefinitly becoming a
    whitelisted IP!/

We have removed the use of the old list.
Instead the banned IP will be logged in a separate ban file:
https://github.com/phoenixweb/ddos-deflate/blob/master/src/ddos.sh#L256-L257

You can see my fork here:
https://github.com/phoenixweb/ddos-deflate


Hope this help!

Bye,
Max



Il 06/08/2015 00:53, Marian Ignev ha scritto:

**Comment by jgmdev** [comment]
Mmm, the whitelisted thing is true, @maxcuttins I like your changes, especially the one to assign max connections to http and ftp, thinking about it maybe we can use bash arrays to control the max connections per port for any port, eg:
```sh
PORTS[0]="80|443"
PORTS[1]="20|21"
PORTS[2]="143"
PORTS_MAX_CONN[0]=80
PORTS_MAX_CONN[1]=120
PORTS_MAX_CONN[2]=200
```
That way the additions of new ports is dynamic on the conf file. Also I was thinking, since there are so many forks of this script, what do you think if some of us creates a github organization exclusively for this script (it seems ddos-deflate is available to use), then every fork should add a note linking to the official and up to date repo with the enhancements of everybody. So anybody that has done substantial work to the script should be added as a member of the ddos-deflate github organization.

**Comment by maxcuttins** [comment]
Hi Jeff,

thank you for sharing your hints.
I see in the dynamic way you proposed many pro in semplify programming 
however i prefer instead use a strict constant env.
This is because we need to do:

HTTP = 80|443
FTP = 20|21|30000:35000
IMAP = 143|993 #do not forget SSL
*ALL = * - FTP - IMAP*

making this dynamic will be really complicated to do:

PORTS[0]=80|443
PORTS[1]=20|21|30000:35000
PORTS[2]=143|993 #do not forget SSL
*ALL= * - PORTS[1] - PORTS[2] *

The ALL connections config specific will becoming unreadable if we 
continue to add [#] ports.
In the end there are not so many services to exclude, I think we can 
still use the static definition of the ports in order to have a clean 
config file ;)

About creating an organization, I've already. :)
My organization need this script to be update quite often.
It's a web hosting company and there is a big need of security.
If you want I can host all the whole project.

Creating a DDOS-DEFLATE organization is better, but i cannot add all my 
team to 2 differents organizations everytime.
We really need to develop this internally. Of course contribute is 
really appreciated.
Let me know, we'll probably try to upgrade this script many and many time.
If you want i can push my changes to your project, for me it's the same! :)

Of course I can add you as external developer to our repo.


*Massimiliano Cuttini*
________________________________
*PhoenixWeb*
Via Donizetti 3
20122 Milano (Italy)

Site: www.pegasohosting.net <http://www.pegasohosting.net>
Tel:    +39 02 5464139
Fax:   +39 02 49665038

/AVVISO DI RISERVATEZZA
Le informazioni contenute nella presente e-mail ed eventualmente negli 
allegati possono essere confidenziali e sono comunque riservate al 
destinatario della stessa.Se aveste ricevuto questa e-mail per errore, 
ci scusiamo per l'accaduto, Vi invitiamo cortesemente a darcene notizia 
e a distruggere il messaggio. La diffusione, l’utilizzo e/o la 
conservazione dei dati ricevuti per errore costituiscono violazioni alle 
disposizioni del D.Lgs.196/03 (Codice della Privacy, in materia di 
protezione dei dati personali)./

Il 07/08/2015 18:41, Jefferson González ha scritto:

**Comment by jgmdev** [comment]
Should be fixed on latest commit, but haven't tested it yet.
