### ISSUE TITLE
ipv6 and ipv4

### ISSUE THREAD

**Issue by oim37** [jgmdev/ddos-deflate#85]
Use DDoS-Deflate version 1.3
OS Centos 7 x64 iptables

Banned the following ip addresses on Sat Mar 26 03:44:09 UTC 2022
::ffff:111.222.111.222 with 386 connections

In iptables nothing, because have wrong ::ffff:

how to fix this, server use both ipv6 and ipv4.

**Comment by persuader** [comment]
I have the same issue with Ubuntu 22.04.

I think the problem is that the ss command shows connection status in this format. 

`tcp                  ESTAB                 0                      0                                       [::ffff:192.168.2.136]:5222                                  [::ffff:192.168.2.137]:50743
`
So when you check the address on line 151 it aways turns to ip6tables. Maybe it will work if you switch to netstat.

P.S.

If you switch to netstat setting SS_MISSING=true in ddos.sh the problem is gone. 
`
